run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt
    - goimports
    - misspell
    - unconvert
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/papermap/papermap-tui
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch

issues:
  exclude-dirs:
    - bin
    - dist
  max-issues-per-linter: 0
  max-same-issues: 0
